name: C/C++ CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: LIST CPU
      run:
        lscpu

    - name: O0
      run:
        make -j9 LONG=1 O0=1 SANITIZE=1

    - name: O1
      run:
        make -j9 LONG=1 O1=1 SANITIZE=1

    - name: O2
      run:
        make -j9 LONG=1 O2=1 SANITIZE=1

    - name: O3
      run:
        make -j9 LONG=1 O3=1 SANITIZE=1

    - name: Og
      run:
        make -j9 LONG=1 Og=1 SANITIZE=1

    - name: Os
      run:
        make -j9 LONG=1 Os=1 SANITIZE=1

    - name: Ofast
      run:
        make -j9 LONG=1 Ofast=1

    - name: O0 (SANITIZE=0)
      run:
        make -j9 LONG=1 O0=1 SANITIZE=0

    - name: O1 (SANITIZE=0)
      run:
        make -j9 LONG=1 O1=1 SANITIZE=0

    - name: O2 (SANITIZE=0)
      run:
        make -j9 LONG=1 O2=1 SANITIZE=0

    - name: O3 (SANITIZE=0)
      run:
        make -j9 LONG=1 O3=1 SANITIZE=0

    - name: Og (SANITIZE=0)
      run:
        make -j9 LONG=1 Og=1 SANITIZE=0

    - name: Os (SANITIZE=0)
      run:
        make -j9 LONG=1 Os=1 SANITIZE=0

    - name: Ofast (SANITIZE=0)
      run:
        make -j9 LONG=1 Ofast=1 SANITIZE=0

    - name: c99
      run:
        make -j9 CC=gcc\ -std=c99

    - name: c11
      run:
        make -j9 CC=gcc\ -std=c11

    - name: examples
      run:
        make examples
